# Generated by Django 2.1.5 on 2019-04-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190408_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.AddField(
            model_name='review',
            name='search',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Search'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
