# Generated by Django 2.1.7 on 2019-04-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190408_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='search',
        ),
        migrations.AlterField(
            model_name='review',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
