# Generated by Django 2.1.5 on 2019-04-09 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190408_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviews',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='core.Review'),
            preserve_default=False,
        ),
    ]
