# Generated by Django 2.1.5 on 2019-04-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
